version: '3.8'

 services:
  web:
    image: nginx
       Frontend:
         build:
          context: ./FrontEnd
          dockerfile: Dockerfile
        ports:
         -"5173:5173"
         depends_on:
         - backend
        environment: 
         - VITE_API_URL=http://localhost:5000

       Backend:
         build:
          context: ./express-backend
          dockerfile: Dockerfile
        ports:
         -"5000:5000"
        depends_on:
        - mongodb
      environmet:
       - MONGO_URI=mongodb://mongodb:27017/mydb
       -CLIENT_URL=http://localhost:5173
       depends_on:
       -mongodb
       volumes:
       - ./backend:/app
       - /app/node_modules

    mongodb:
     image: mongo:latest
     ports:
        -"27017:27017"
        volumes:
         - mongo-data:data/db
         volumes:
         mongo-data:
       
